{"name": "test_buy_gtai_link_redirects_to_correct_url[chromium]", "status": "failed", "statusDetails": {"message": "AssertionError: Page URL expected to be 'https://www.bybit.com/en/trade/spot/GTAI/USDT?affiliate_id=71085&ref_code=GTPROTOCOL'\nActual value: chrome-error://chromewebdata/ \nCall log:\nPageAssertions.to_have_url with timeout 5000ms\n  - waiting for locator(\":root\")\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"chrome-error://chromewebdata/\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"chrome-error://chromewebdata/\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"chrome-error://chromewebdata/\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"chrome-error://chromewebdata/\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"chrome-error://chromewebdata/\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"chrome-error://chromewebdata/\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"chrome-error://chromewebdata/\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"chrome-error://chromewebdata/\"\n  -   locator resolved to <html>…</html>\n  -   unexpected value \"chrome-error://chromewebdata/\"", "trace": "page = <Page url='https://www.gt-protocol.io/'>\n\n    def test_buy_gtai_link_redirects_to_correct_url(page: Page):\n        page.goto(\"https://www.gt-protocol.io/\")\n    \n        with page.context.expect_page() as new_page_info:\n            page.click(\"text=Buy $GTAI\")\n        new_page = new_page_info.value\n    \n        expected_url = \"https://www.bybit.com/en/trade/spot/GTAI/USDT?affiliate_id=71085&ref_code=GTPROTOCOL\"  # Replace with actual URL\n>       expect(new_page).to_have_url(expected_url)\nE       AssertionError: Page URL expected to be 'https://www.bybit.com/en/trade/spot/GTAI/USDT?affiliate_id=71085&ref_code=GTPROTOCOL'\nE       Actual value: chrome-error://chromewebdata/ \nE       Call log:\nE       PageAssertions.to_have_url with timeout 5000ms\nE         - waiting for locator(\":root\")\nE         -   locator resolved to <html>…</html>\nE         -   unexpected value \"chrome-error://chromewebdata/\"\nE         -   locator resolved to <html>…</html>\nE         -   unexpected value \"chrome-error://chromewebdata/\"\nE         -   locator resolved to <html>…</html>\nE         -   unexpected value \"chrome-error://chromewebdata/\"\nE         -   locator resolved to <html>…</html>\nE         -   unexpected value \"chrome-error://chromewebdata/\"\nE         -   locator resolved to <html>…</html>\nE         -   unexpected value \"chrome-error://chromewebdata/\"\nE         -   locator resolved to <html>…</html>\nE         -   unexpected value \"chrome-error://chromewebdata/\"\nE         -   locator resolved to <html>…</html>\nE         -   unexpected value \"chrome-error://chromewebdata/\"\nE         -   locator resolved to <html>…</html>\nE         -   unexpected value \"chrome-error://chromewebdata/\"\nE         -   locator resolved to <html>…</html>\nE         -   unexpected value \"chrome-error://chromewebdata/\"\n\ntests/test_navigation.py:117: AssertionError"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1730385303357, "stop": 1730385311845, "uuid": "29660948-23ed-4687-8ca9-33f0342a6238", "historyId": "ad8c3ae60cc3e799caa0510fa0d785f9", "testCaseId": "5278b24a156527efb37b8a3f8865c321", "fullName": "tests.test_navigation#test_buy_gtai_link_redirects_to_correct_url", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_navigation"}, {"name": "host", "value": "MBP-Igor"}, {"name": "thread", "value": "44149-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_navigation"}]}